# path to the image root folder containing multiple image folders: images1/, images2/ etc.
data_path: /app/alexw/Experements/Imaginova
# /app/alexw/Experements/Imaginova
# /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation


# one or more (comma separated) .csv files, containing columns <paths> and <captions>
csv_list:
    # - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/main_data/mj_RENEW_corrected.csv
    - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/toy_data/images1.csv
    - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/toy_data/images2.csv
    - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/toy_data/images3.csv


# image crop box
crop_box: [0, 0, 1024, 1024]


model:
    pretrained_checkpoint: "blip2-opt-2.7b"
    checkpoint_root: /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/base_model_checkpoints

peft:
    add_adapter: false
    checkpoint_root: /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/peft_checkpoints
    lora:
        r: 16
        lora_alpha: 32
        lora_dropout: 0.05
        target_modules: ["q_proj", "k_proj"]
        bias: "none"


# training params
training:
    learning_rate: 5.0e-5
    n_epochs: 10
    batch_size: 1
    gradient_accumulation_steps: 8
    dataloader_workers: 32


# logging params
logging:
    checkpoint_path: # updated in code
    checkpoint_every_nth_epoch: 5
    wandb:
        enabled: false
        project: "BLIP2_FINETUNE"
     
    