# path to the image root folder containing multiple image folders: images1/, images2/ etc.
data_path: /app/alexw/Experements/Imaginova
# /app/alexw/Experements/Imaginova
# /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation
#
# one or more (comma separated) .csv files, containing columns <paths> and <captions>
csv_list: 
    - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/mj_RENEW_corrected.csv
    # - /app/alexw/Experements/Imaginova/mj_RENEW.csv
    # - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/images1.csv
    # - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/images2.csv
    # - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/images3.csv

# image crop box
crop_box: [0, 0, 1024, 1024]

#model params
model:
    pretrained: "blip2-opt-2.7b"
    
peft:
    checkpoint_root: /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/peft_checkpoints
    # updated during training
    checkpoint_path:
    lora:
        r: 16
        lora_alpha: 32
        lora_dropout: 0.05
        target_modules: ["q_proj", "k_proj"]
        bias: "none"
        

# training params
training:
    learning_rate: 5.0e-5
    n_epochs: 10
    batch_size: 2

# W&B params
wandb:
    enabled: true
    project: "BLIP2_FINETUNE"
    