data:
    # path to the image root folder containing multiple image folders: images1/, images2/ etc.
    path: /app/alexw/Experements/Imaginova
        # /app/alexw/Experements/Imaginova
        # /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation

    # one or more (comma separated) .csv files, containing columns <paths> and <captions>
    csv_list:
        - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/main_data/mj_RENEW_corrected.csv
        # - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/toy_data/images1.csv
        # - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/toy_data/images2.csv
        # - /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/data/toy_data/images3.csv

    # image crop box
    crop_box: [0, 0, 1024, 1024]


# Loads pretrained base model and adds an adapter if model.adapter.add_adapter is true.
# Loads the adapter from models.adapter.checkpoint if model.adapter.load_from_checkpoint is true,
# otherwise builds the adapter from scratch.
# Unfreezes model's parts if required.
model:
    processor: "blip2-opt-2.7b"
    base_model:
        checkpoint: "blip2-opt-2.7b"
        unfreeze_language_model: false
        unfreeze_vision_model: false
        unfreeze_qformer: true
        unfreeze_language_projection: true
    adapter:
        add_adapter: false
        load_from_checkpoint: false
        checkpoint: 
        lora_config:
            r: 16
            lora_alpha: 32
            lora_dropout: 0.05
            target_modules: ["q_proj", "k_proj"]
            bias: "none"


training:
    learning_rate: 5.0e-5
    n_epochs: 12
    batch_size: 1
    gradient_accumulation_steps: 8
    dataloader_workers: 16


# log_base_model=false used when base model is frozen to obtain lightweight checkpoints
logging:
    checkpoint_root: /app/alexw/Experements/Imaginova/sergey_blip_dataset_creation/model_checkpoints
    checkpoint_path: # updated in code
    
    log_base_model: true
    
    checkpoint_every_nth_epoch: 3
    wandb:
        enabled: true
        project: "BLIP2_FINETUNE"
     
    